# This is based on a sample YAML file from the Electron Builder documentation:
# https://github.com/develar/onshape-desktop-shell/blob/master/.travis.yml

# Specify the different builds
matrix:
  include:
    - os: osx
      osx_image: xcode9.0
      language: node_js
      node_js: "8"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

# These directories will be cached between subsequent builds
cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

before_install:
  - |
    wget https://isaacracing.net/public/steamworks_sdk.tar.gz && mkdir -p Zamiell/isaac-racing-client/node_modules/greenworks/deps && tar xzf steamworks_sdk.tar.gz --directory Zamiell/isaac-racing-client/node_modules/greenworks/deps
    echo Step 1
    ls -l
    echo Step 2
    ls -l Zamiell
    echo Step 3
    ls -l Zamiell/isaac-racing-client
    echo Step 4
    ls -l Zamiell/isaac-racing-client/node_modules
    echo Step 5
    ls -l Zamiell/isaac-racing-client/node_modules/greenworks
    echo Step 6
    ls -l Zamiell/isaac-racing-client/node_modules/greenworks/deps
    echo Step 7
    ls -l Zamiell/isaac-racing-client/node_modules/greenworks/deps/steamworks_sdk